"""
Example: Python data pipeline to TypeScript

Before (Python):
    import json
    from pathlib import Path

    def load_config(path: str) -> dict:
        with open(path) as f:
            return json.load(f)

    def transform_data(records: list) -> list:
        results = []
        for record in records:
            if record.get("active"):
                results.append({
                    "id": record["id"],
                    "name": record["name"].strip().title(),
                    "score": round(record["raw_score"] * 1.1, 2),
                })
        return sorted(results, key=lambda x: x["score"], reverse=True)

    def save_report(data: list, output_path: str) -> None:
        with open(output_path, "w") as f:
            json.dump(data, f, indent=2)
        print(f"Saved {len(data)} records to {output_path}")

    if __name__ == "__main__":
        config = load_config("config.json")
        raw = load_config(config["input_file"])
        processed = transform_data(raw)
        save_report(processed, config["output_file"])


After (TypeScript) — generated by CodeMorph:

    import * as fs from "fs";

    interface Config {
        inputFile: string;
        outputFile: string;
    }

    interface RawRecord {
        id: number;
        name: string;
        raw_score: number;
        active: boolean;
    }

    interface ProcessedRecord {
        id: number;
        name: string;
        score: number;
    }

    function loadConfig(path: string): any {
        return JSON.parse(fs.readFileSync(path, "utf-8"));
    }

    function transformData(records: RawRecord[]): ProcessedRecord[] {
        const results: ProcessedRecord[] = [];
        for (const record of records) {
            if (record.active) {
                results.push({
                    id: record.id,
                    name: record.name.trim().replace(/\b\w/g, (c) => c.toUpperCase()),
                    score: Math.round(record.raw_score * 1.1 * 100) / 100,
                });
            }
        }
        return results.sort((a, b) => b.score - a.score);
    }

    function saveReport(data: ProcessedRecord[], outputPath: string): void {
        fs.writeFileSync(outputPath, JSON.stringify(data, null, 2));
        console.log(`Saved ${data.length} records to ${outputPath}`);
    }

    if (require.main === module) {
        const config: Config = loadConfig("config.json");
        const raw: RawRecord[] = loadConfig(config.inputFile);
        const processed = transformData(raw);
        saveReport(processed, config.outputFile);
    }

Usage:
    codemorph migrate ./data-pipeline --target typescript --output ./ts-pipeline
"""
