"""
Example: Flask API to Express.js

Before (Python/Flask):
    from flask import Flask, jsonify, request

    app = Flask(__name__)

    users = [
        {"id": 1, "name": "Alice", "email": "alice@example.com"},
        {"id": 2, "name": "Bob", "email": "bob@example.com"},
    ]

    @app.route("/api/users", methods=["GET"])
    def get_users():
        return jsonify(users)

    @app.route("/api/users/<int:user_id>", methods=["GET"])
    def get_user(user_id):
        user = next((u for u in users if u["id"] == user_id), None)
        if user is None:
            return jsonify({"error": "Not found"}), 404
        return jsonify(user)

    @app.route("/api/users", methods=["POST"])
    def create_user():
        data = request.json
        new_user = {
            "id": len(users) + 1,
            "name": data["name"],
            "email": data["email"],
        }
        users.append(new_user)
        return jsonify(new_user), 201

    if __name__ == "__main__":
        app.run(debug=True)


After (TypeScript/Express) — generated by CodeMorph:

    import express, { Request, Response } from "express";

    const app = express();
    app.use(express.json());

    interface User {
        id: number;
        name: string;
        email: string;
    }

    const users: User[] = [
        { id: 1, name: "Alice", email: "alice@example.com" },
        { id: 2, name: "Bob", email: "bob@example.com" },
    ];

    app.get("/api/users", (req: Request, res: Response) => {
        res.json(users);
    });

    app.get("/api/users/:userId", (req: Request, res: Response) => {
        const userId = parseInt(req.params.userId);
        const user = users.find((u) => u.id === userId);
        if (!user) {
            res.status(404).json({ error: "Not found" });
            return;
        }
        res.json(user);
    });

    app.post("/api/users", (req: Request, res: Response) => {
        const data = req.body;
        const newUser: User = {
            id: users.length + 1,
            name: data.name,
            email: data.email,
        };
        users.push(newUser);
        res.status(201).json(newUser);
    });

    app.listen(3000, () => console.log("Server running on port 3000"));

Usage:
    codemorph migrate ./flask-api --target typescript --output ./express-api
"""
